#!/usr/bin/python
import argparse
import sys
import simulation
import viz
from conf import msg
#-------------------------------------------------------------------------------
DEFAULT_VIZ_CFG_FILE = "conf/visualization.json"
#-------------------------------------------------------------------------------
if __name__ ==  '__main__':
    parser = argparse.ArgumentParser('ineract')
    parser.add_argument('-l', dest='log', action='store_true',
                        help='Write to a log file')
    parser.add_argument('--cfg-viz', dest='cfg_viz',
                        default=DEFAULT_VIZ_CFG_FILE,
                        help='Configuration file for the visualization')
    args = parser.parse_args()
    # Create and prepare the simulation
    sim = simulation.Simulation()
    if not sim.load():
        sys.stderr.write(msg.sim_load_fail + msg.newline)
        sys.exit(1)
    # Start the visualisation
    viz = viz.Visualization(sim)
    viz.configure(args.cfg_viz)
    viz.start()
