#!/usr/bin/python
import argparse
import sim
import viz
#-------------------------------------------------------------------------------
DEFAULT_VIZ_CFG_FILE = "conf/visualization.json"
#-------------------------------------------------------------------------------
if __name__ ==  '__main__':
    parser = argparse.ArgumentParser('ineract')
    parser.add_argument('-l', dest='log', action='store_true',
                        help='Write to a log file')
    parser.add_argument('-c', dest='vizCfgFilename',
                        default=DEFAULT_VIZ_CFG_FILE,
                        help='Configuration file for the visualization')
    parser.add_argument(dest='worldCfgFilename')
    args = parser.parse_args()
    # Create and prepare the simulation
    simulation = sim.Simulation()
#    simulation.load(args.worldCfgFilename)
    simulation.configure(args.worldCfgFilename)
    simulation.load()
    # Start the visualisation
    viz = viz.Visualization(simulation)
    viz.configure(args.vizCfgFilename)
    viz.start()
